spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database.cz02ckmiuje0.ap-southeast-2.rds.amazonaws.com:3306/spring_member_db
    username: admin
    password: commarket

server:
  port: 8085